/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SphereDistributorInterface extends Interface {
  getFunction(nameOrSignature: "distribute" | "transfer"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Distribution" | "SingleTransfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "distribute",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
}

export namespace DistributionEvent {
  export type InputTuple = [
    sender: AddressLike,
    token: AddressLike,
    totalAmount: BigNumberish,
    recipientCount: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    token: string,
    totalAmount: bigint,
    recipientCount: bigint
  ];
  export interface OutputObject {
    sender: string;
    token: string;
    totalAmount: bigint;
    recipientCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SingleTransferEvent {
  export type InputTuple = [
    sender: AddressLike,
    token: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    token: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    sender: string;
    token: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SphereDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): SphereDistributor;
  waitForDeployment(): Promise<this>;

  interface: SphereDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  distribute: TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  transfer: TypedContractMethod<
    [token: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "distribute"
  ): TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [token: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Distribution"
  ): TypedContractEvent<
    DistributionEvent.InputTuple,
    DistributionEvent.OutputTuple,
    DistributionEvent.OutputObject
  >;
  getEvent(
    key: "SingleTransfer"
  ): TypedContractEvent<
    SingleTransferEvent.InputTuple,
    SingleTransferEvent.OutputTuple,
    SingleTransferEvent.OutputObject
  >;

  filters: {
    "Distribution(address,address,uint256,uint256)": TypedContractEvent<
      DistributionEvent.InputTuple,
      DistributionEvent.OutputTuple,
      DistributionEvent.OutputObject
    >;
    Distribution: TypedContractEvent<
      DistributionEvent.InputTuple,
      DistributionEvent.OutputTuple,
      DistributionEvent.OutputObject
    >;

    "SingleTransfer(address,address,address,uint256)": TypedContractEvent<
      SingleTransferEvent.InputTuple,
      SingleTransferEvent.OutputTuple,
      SingleTransferEvent.OutputObject
    >;
    SingleTransfer: TypedContractEvent<
      SingleTransferEvent.InputTuple,
      SingleTransferEvent.OutputTuple,
      SingleTransferEvent.OutputObject
    >;
  };
}
