/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SphereAgentWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agent"
      | "budgets"
      | "fund"
      | "isActive"
      | "owner"
      | "refund"
      | "remainingBudget"
      | "setAgent"
      | "spend"
      | "spent"
      | "startSession"
      | "stopAndRefund"
      | "totalSpent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentSet"
      | "Funded"
      | "Refunded"
      | "SessionStarted"
      | "SessionStopped"
      | "Spent"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "budgets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fund",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "remainingBudget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "spend",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "spent", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "startSession",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stopAndRefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSpent",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "agent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "budgets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remainingBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopAndRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalSpent", data: BytesLike): Result;
}

export namespace AgentSetEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionStartedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionStoppedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpentEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SphereAgentWallet extends BaseContract {
  connect(runner?: ContractRunner | null): SphereAgentWallet;
  waitForDeployment(): Promise<this>;

  interface: SphereAgentWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agent: TypedContractMethod<[], [string], "view">;

  budgets: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  fund: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  isActive: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  remainingBudget: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  setAgent: TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  spend: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  spent: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  startSession: TypedContractMethod<[], [void], "nonpayable">;

  stopAndRefund: TypedContractMethod<[], [void], "nonpayable">;

  totalSpent: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "budgets"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "remainingBudget"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "spend"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "spent"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "startSession"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stopAndRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalSpent"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getEvent(
    key: "AgentSet"
  ): TypedContractEvent<
    AgentSetEvent.InputTuple,
    AgentSetEvent.OutputTuple,
    AgentSetEvent.OutputObject
  >;
  getEvent(
    key: "Funded"
  ): TypedContractEvent<
    FundedEvent.InputTuple,
    FundedEvent.OutputTuple,
    FundedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "SessionStarted"
  ): TypedContractEvent<
    SessionStartedEvent.InputTuple,
    SessionStartedEvent.OutputTuple,
    SessionStartedEvent.OutputObject
  >;
  getEvent(
    key: "SessionStopped"
  ): TypedContractEvent<
    SessionStoppedEvent.InputTuple,
    SessionStoppedEvent.OutputTuple,
    SessionStoppedEvent.OutputObject
  >;
  getEvent(
    key: "Spent"
  ): TypedContractEvent<
    SpentEvent.InputTuple,
    SpentEvent.OutputTuple,
    SpentEvent.OutputObject
  >;

  filters: {
    "AgentSet(address)": TypedContractEvent<
      AgentSetEvent.InputTuple,
      AgentSetEvent.OutputTuple,
      AgentSetEvent.OutputObject
    >;
    AgentSet: TypedContractEvent<
      AgentSetEvent.InputTuple,
      AgentSetEvent.OutputTuple,
      AgentSetEvent.OutputObject
    >;

    "Funded(address,uint256)": TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;
    Funded: TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;

    "Refunded(address,address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "SessionStarted()": TypedContractEvent<
      SessionStartedEvent.InputTuple,
      SessionStartedEvent.OutputTuple,
      SessionStartedEvent.OutputObject
    >;
    SessionStarted: TypedContractEvent<
      SessionStartedEvent.InputTuple,
      SessionStartedEvent.OutputTuple,
      SessionStartedEvent.OutputObject
    >;

    "SessionStopped()": TypedContractEvent<
      SessionStoppedEvent.InputTuple,
      SessionStoppedEvent.OutputTuple,
      SessionStoppedEvent.OutputObject
    >;
    SessionStopped: TypedContractEvent<
      SessionStoppedEvent.InputTuple,
      SessionStoppedEvent.OutputTuple,
      SessionStoppedEvent.OutputObject
    >;

    "Spent(address,address,uint256)": TypedContractEvent<
      SpentEvent.InputTuple,
      SpentEvent.OutputTuple,
      SpentEvent.OutputObject
    >;
    Spent: TypedContractEvent<
      SpentEvent.InputTuple,
      SpentEvent.OutputTuple,
      SpentEvent.OutputObject
    >;
  };
}
